### ISSUE TITLE
Removing Elevator

### ISSUE THREAD

**Issue by pjalm** [Vexatos/Thut#2]
Destroying any block causes the elevator to go wonky and u can't remove it.

**Comment by Vexatos** [comment]
The elevator does need to be connected to full railing. Just place the elevator rail you broke and it should work again.

**Comment by pjalm** [comment]
I wanted to delete the elevator not fix it though. Is there a special way to remove it?

**Comment by Vexatos** [comment]
Shift-right click the bottom center of the elevator with any kind of wrench or a Vanilla Stick.

**Comment by pjalm** [comment]
ok that worked thx
